### ISSUE TITLE
Improve and refactor Markdown linting pipeline (OSOE-405)

### ISSUE THREAD

**Issue by 0liver** [Lombiq/NodeJs-Extensions#14]
After OSOE-92 has been merged.

### Problem

Currently, _lint-markdown.js_ uses `markdownlint.sync()` to lint markdown files.

The release notes for [version 0.21.0](https://github.com/DavidAnson/markdownlint#:~:text=lint%20concurrently%20for%20better%20performance%20(async%20only)) of `markdownlint` mention:
> Lint concurrently for better performance (async only)

Let's use that.

Another reason to use the async version is that it takes a [callback](https://github.com/DavidAnson/markdownlint#callback) that receives both **Error** and **Result** objects. In the error case, we can then use `handleError` the same way that we do for `textlint`.

### Additional improvements
- Use `handleErrorMessage` from _handle-error,.js_ on `throw new Error("Couldn't find a .NET solution (.sln) file.");`.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-405)

**Comment by sarahelsaig** [comment]
> Another reason to use the async version is that it takes a [callback](https://github.com/DavidAnson/markdownlint#callback) that receives both Error and Result objects.

That's not actually an advantage, the way the sync version behaves (by throwing the Error object) is much cleaner. Luckily we can use the promise version which behaves just like the sync version (so rejecting the promise and passing the Error object) but it still uses the async version under the hood. This is achieved simply by passing it through Node.JS's [promisify](https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original) utility. The `useTextLint()` in the same file is already a Promise-based task, so this way they are both handled the same.

> Use handleErrorMessage from handle-error,.js on throw new Error("Couldn't find a .NET solution (.sln) file.");.

That's not necessary. When the `throw` happens it's caught and passed to `handleError` [here](https://github.com/Lombiq/NodeJs-Extensions/blob/dev/Lombiq.NodeJs.Extensions/scripts/lint-markdown.js#L123-L125). This is superior to using `handleError` directly, because if we did that we'd have to follow with `process.exit()` to achieve the same result of stopping everything after it. In both cases my argument is that it's preferable to use vanilla JS syntax wherever possible.

**Comment by 0liver** [comment]
Beware that I've changed the whole Markdown linting execution approach in OSOE-84 by now to conform to the other pipelines, so please try not to touch that part (too much). The inner linting "engine" is staying as is, but the invocation works differently now.

**Comment by 0liver** [comment]
Fixed by https://github.com/Lombiq/NodeJs-Extensions/pull/20.
