### ISSUE TITLE
ExecWithMutex (OSOE-613)

### ISSUE THREAD

**Issue by PabloSergi** [Lombiq/NodeJs-Extensions#45]
Hi friends, I will duplicate this question here, it seems to me that it probably goes more to you than to OrchardCore. But the problem I have is with their cms. 

I am learning c# not so long ago. Sorry if this is a beginner's question, but I seem to have read everything carefully and searched the internet for a long time, but haven't found anything about my problem. I'm learning c# on my m1 mac and don't have an update to the latest version at the moment. Decided to try creating an online store today, downloaded OrchardCore and OrchardCore.Commerce. The first one works, the second one gives the following error.

/Users/pablo_sergi/.nuget/packages/lombiq.nodejs.extensions/1.2.2/Lombiq.NodeJs.Extensions.targets(5,5): Error MSB4216: Could not run the "ExecWithMutex" task because MSBuild could not create or connect to a task host with runtime "NET" and architecture "arm64". Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "MSBuild.exe" exists and can be run. (MSB4216) (OrchardCore.Commerce)

I updated nuget, the error remains. Not quite sure what to do about it. It seems to be a lombiq.nodejs.extensions compatibility issue? How do I fix this in general?

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-613)

**Comment by 0liver** [comment]
Hi @PabloSergi, thanks for reaching out! Glad to have you trying out Orchard Core and OrchardCore.Commerce, too.

You are probably the first person out there to try out Lombiq Node.js Extensions on an ARM64 CPU, and I don't have an answer ready for you how to fix the build error you're seeing. You might have to install some additional components for your CPU to make this work.

There is also a different approach to fixing this problem that might be feasible. The `ExecWithMutex` task has been introduced to address some concurrency problems with the Windows file system. Since you're not on Windows, you might get away without that special task. It would actually be a good idea to introduce this change into this project, but I'm not sure how soon we'll be able to get around to adding it.

In the meantime, here's what you can try:
1. In your NuGet cache folder, under _/Users/pablo_sergi/.nuget/packages/lombiq.nodejs.extensions/1.2.2_, replace all occurrences of `ExecWithMutex` with just `Exec`.
2. Build your solution.

Please report back whether that helps.

**Comment by PabloSergi** [comment]
Good afternoon, i checked it, after these actions " replace all occurrences of ExecWithMutex with just Exec." - now its working. Thank you very much) I can't be sure yet that everything works correctly, at least not like the guys in the attached video at orchardcore.commerce, but that may be because I did something wrong yesterday with the sdk .net arm64/x64 etc. Anyway, in the next day I will study it in more detail and report if everything is ok. But already very cool that it works at all, thanks again! 

UPD.
Checked it, it's working properly. Thank you)

**Comment by Piedone** [comment]
Should we make these execs conditional based on the platform then, Oliver?

**Comment by Piedone** [comment]
Also, this is only for ARM, right?

**Comment by 0liver** [comment]
> Should we make these execs conditional based on the platform then, Oliver?

You've read my mind! Yes, those workarounds are actually only needed on Windows.

I will address that in OSOE-593.

**Comment by Piedone** [comment]
This was fixed in https://github.com/Lombiq/NodeJs-Extensions/pull/47 and v1.2.3 also contains it.
