### ISSUE TITLE
Update NPM dependencies to latest, and fix them (OSOE-671)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/NodeJs-Extensions#67]
Update all the NPM dependencies of the package to the latest versions, and make sure that the version numbers are not open but fixed to a specific version to avoid issues like https://github.com/Lombiq/Orchard-Base-Theme/issues/84.

Note that updating `sass` to v1.65.1 causes this issue: https://github.com/Lombiq/Orchard-Base-Theme/issues/84. If Bootstrap has a fix (https://github.com/twbs/bootstrap/issues/39028) and we can update it in Base Theme, then do that; otherwise, keep `sass` on the latest still compatible version.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-671)

**Comment by wAsnk** [comment]
Updating stylelint to 15.10.3 from 14.14.0 would mean a major update that contains the following (breaking) changes:
[https://stylelint.io/migration-guide/to-15](https://stylelint.io/migration-guide/to-15)

To sum up, they deprecated 76 rules because they are mostly styling related rules that can be achieved by pretty printers like Prettier so they won't support it anymore from the next major update.

Edit
These are the rules that we are using and deprecated:
```
'declaration-block-semicolon-newline-before': 'never-multi-line',
'function-comma-newline-after': 'always-multi-line',
'indentation': 4,
'max-line-length': 150,
'selector-list-comma-space-after': 'always-single-line',
'selector-list-comma-newline-after': 'always-multi-line',
'value-list-comma-newline-before': 'never-multi-line'
```

What should be done in this case?

**Comment by Piedone** [comment]
Eh, thanks for looking into this. Let's update to the latest 14.x for now then, and later we can look into upgrading to 15.x and see whether we should use Prettier or something.

**Comment by wAsnk** [comment]
Alright, then the stylelint-config-standard-scss package max version can be 6.1.0, because the next version (7.0.0) requires stylelint 15.x.
